name: Fetch MySQL Dynamic Secrets
'on': push
jobs:
  fetch_mysql_dynamic_secrets:
    runs-on: self-hosted
    name: Fetch MySQL Dynamic Secrets
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Fetch dynamic secrets from Akeyless
        id: fetch-dynamic-secrets
        uses: akeyless-community/akeyless-github-action@v1.0.1
        with:
          access-id: '${{ secrets.ACCESS_ID }}'
          dynamic-secrets: |
            - name: "/github/mydynamicsecret"
              output-name: "mysql_dynamic_secret"
          access-type: jwt
          export-secrets-to-outputs: true
          export-secrets-to-environment: true
          api-url: 'https://csm.thalescryptolabs.com/akeyless-api/v2/'
      - name: Export Secrets to Environment
        run: >
          echo '${{ steps.fetch-dynamic-secrets.outputs.mysql_dynamic_secret
          }}' | jq -r
          'to_entries|map("MYSQL_\(.key|ascii_upcase)=\(.value|tostring)")|.[]'
          >> $GITHUB_ENV
      - name: Verify Vars
        run: >
          echo "host: ${{ env.MYSQL_HOST }}" >> secrets.txt
          echo "port: ${{ env.MYSQL_PORT }}" >> secrets.txt
          echo "username: ${{ env.MYSQL_USER }}" >> secrets.txt
          echo "password: ${{ env.MYSQL_PASSWORD }}" >> secrets.txt
          echo "db_name: ${{ env.MYSQL_DB_NAME }}" >> secrets.txt
          echo "ttl_in_minutes: ${{ env.MYSQL_TTL_IN_MINUTES }}" >>
          secrets.txt     
